#!/usr/bin/env bash
# Install Nginx and allow HTTP traffic
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# Create a directory for your web content
mkdir -p /var/www/html/
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

# Define the redirection configuration
REDIRECT_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.google.com;
    }
}"

# Add the redirection configuration to the default server block
echo "$REDIRECT_CONFIG" > /etc/nginx/sites-enabled/default

# Restart Nginx without using systemctl
nginx_pid=$(cat /var/run/nginx.pid)
if [ -z "$nginx_pid" ]; then
    service nginx start
else
    service nginx restart
fi
