#!/usr/bin/env bash
#configure a custom 404 page

echo "<html><body><h1>Ceci n'est pas une page</h1></body></html>" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom error page for 404 errors
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Restart Nginx
service nginx restart

# Verify if custom 404 page contains the required string
if grep -q "Ceci n'est pas une page" /usr/share/nginx/html/404.html; then
    echo "Custom 404 page contains 'Ceci n'est pas une page'"
else
    echo "Custom 404 page does not contain 'Ceci n'est pas une page'"
fi
