#!/usr/bin/env bash
# Update Nginx package lists
sudo apt-get update

# Check if Nginx is already installed
if [[ $(dpkg-query -l nginx | grep installed) ]]; then
  echo "Nginx is already installed."
else
  # Install Nginx if not present
  echo "Installing Nginx..."
  sudo apt-get install -y nginx || {
    echo "Error installing Nginx. Please check package repositories and try again."
    exit 1
  }
fi

# Add custom response header (X-Served-By)
escaped_hostname=$(hostname | sed 's/[^\w\-_]//g')
sudo sed -i "/server_name _/a  add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Test Nginx configuration for errors
sudo nginx -t || {
  echo "Error in Nginx configuration. Please check the logs (/etc/nginx/error.log) and make corrections."
  exit 1
}

# Reload Nginx
sudo service nginx reload
sudo service nginx restart

echo "Nginx configuration complete!"

#Check if script is working
curl -sI 18.235.255.90 | grep X-Served-By
