#!/bin/bash
# Configure Nginx to add a custom header with the hostname of the server

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Get the hostname of the server
HOSTNAME=$(428422-web-02)

# Create a configuration snippet to add the custom header
echo "add_header X-Served-By $HOSTNAME;" | sudo tee /etc/nginx/snippets/custom_header.conf

# Modify the Nginx configuration to include the custom header
sudo sed -i '/server_name _;/a include snippets/custom_header.conf;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
