#!/bin/bash
# Update package lists
sudo apt update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Configure hostname
HOSTNAME="${428422}-lb-01"
sudo hostnamectl set-hostname "$HOSTNAME"

# Install HAproxy
sudo apt install haproxy

# Backup default configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAproxy
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0 info
    maxconn 4000
    user haproxy
    group haproxy
    stats timeout 2m
    stats socket /var/lib/haproxy/stats.sock
    stats realm HAProxy Statistics
    stats auth HAPlb01

defaults
    mode http
    option httplog
    balance roundrobin
    option httpcheck

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    option httpchk
    http-check uri /healthcheck path / OK
    balance roundrobin
    server web-01 428422-web-01:80 weight 1 maxconn 200
    server web-02 428422-web-02:80 weight 1 maxconn 200
EOF

# Enable and start HAproxy service
sudo service haproxy enable
sudo service haproxy start

# Verify service status
sudo service haproxy status
